export default {
  login: "Albert-Byrone",
  id: 30287402,
  node_id: "MDQ6VXNlcjMwMjg3NDAy",
  avatar_url: "https://avatars3.githubusercontent.com/u/30287402?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Albert-Byrone",
  html_url: "https://github.com/Albert-Byrone",
  followers_url: "https://api.github.com/users/Albert-Byrone/followers",
  following_url: "https://api.github.com/users/Albert-Byrone/following{/other_user}",
  gists_url: "https://api.github.com/users/Albert-Byrone/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Albert-Byrone/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Albert-Byrone/subscriptions",
  organizations_url: "https://api.github.com/users/Albert-Byrone/orgs",
  repos_url: "https://api.github.com/users/Albert-Byrone/repos",
  events_url: "https://api.github.com/users/Albert-Byrone/events{/privacy}",
  received_events_url: "https://api.github.com/users/Albert-Byrone/received_events",
  type: "User",
  site_admin: false,
  name: "Albert Byrone",
  company: "Moringa School",
  blog: "https://albertbyrone.surge.sh/",
  location: "Nairobi-Kenya",
  email: null,
  hireable: true,
  bio: "Web Developer",
  twitter_username: null,
  public_repos: 62,
  public_gists: 0,
  followers: 13,
  following: 6,
  created_at: "2017-07-19T09:06:20Z",
  updated_at: "2020-12-23T08:16:05Z"
};
