export default [
  {
  login: "bryomajor",
  id: 15925642,
  node_id: "MDQ6VXNlcjE1OTI1NjQy",
  avatar_url: "https://avatars1.githubusercontent.com/u/15925642?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/bryomajor",
  html_url: "https://github.com/bryomajor",
  followers_url: "https://api.github.com/users/bryomajor/followers",
  following_url: "https://api.github.com/users/bryomajor/following{/other_user}",
  gists_url: "https://api.github.com/users/bryomajor/gists{/gist_id}",
  starred_url: "https://api.github.com/users/bryomajor/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/bryomajor/subscriptions",
  organizations_url: "https://api.github.com/users/bryomajor/orgs",
  repos_url: "https://api.github.com/users/bryomajor/repos",
  events_url: "https://api.github.com/users/bryomajor/events{/privacy}",
  received_events_url: "https://api.github.com/users/bryomajor/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "ThukuWakogi",
  id: 16945309,
  node_id: "MDQ6VXNlcjE2OTQ1MzA5",
  avatar_url: "https://avatars2.githubusercontent.com/u/16945309?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ThukuWakogi",
  html_url: "https://github.com/ThukuWakogi",
  followers_url: "https://api.github.com/users/ThukuWakogi/followers",
  following_url: "https://api.github.com/users/ThukuWakogi/following{/other_user}",
  gists_url: "https://api.github.com/users/ThukuWakogi/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ThukuWakogi/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ThukuWakogi/subscriptions",
  organizations_url: "https://api.github.com/users/ThukuWakogi/orgs",
  repos_url: "https://api.github.com/users/ThukuWakogi/repos",
  events_url: "https://api.github.com/users/ThukuWakogi/events{/privacy}",
  received_events_url: "https://api.github.com/users/ThukuWakogi/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "EKibet",
  id: 20268029,
  node_id: "MDQ6VXNlcjIwMjY4MDI5",
  avatar_url: "https://avatars3.githubusercontent.com/u/20268029?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/EKibet",
  html_url: "https://github.com/EKibet",
  followers_url: "https://api.github.com/users/EKibet/followers",
  following_url: "https://api.github.com/users/EKibet/following{/other_user}",
  gists_url: "https://api.github.com/users/EKibet/gists{/gist_id}",
  starred_url: "https://api.github.com/users/EKibet/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/EKibet/subscriptions",
  organizations_url: "https://api.github.com/users/EKibet/orgs",
  repos_url: "https://api.github.com/users/EKibet/repos",
  events_url: "https://api.github.com/users/EKibet/events{/privacy}",
  received_events_url: "https://api.github.com/users/EKibet/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "WaMungai",
  id: 55139857,
  node_id: "MDQ6VXNlcjU1MTM5ODU3",
  avatar_url: "https://avatars2.githubusercontent.com/u/55139857?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/WaMungai",
  html_url: "https://github.com/WaMungai",
  followers_url: "https://api.github.com/users/WaMungai/followers",
  following_url: "https://api.github.com/users/WaMungai/following{/other_user}",
  gists_url: "https://api.github.com/users/WaMungai/gists{/gist_id}",
  starred_url: "https://api.github.com/users/WaMungai/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/WaMungai/subscriptions",
  organizations_url: "https://api.github.com/users/WaMungai/orgs",
  repos_url: "https://api.github.com/users/WaMungai/repos",
  events_url: "https://api.github.com/users/WaMungai/events{/privacy}",
  received_events_url: "https://api.github.com/users/WaMungai/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "ndonyemark",
  id: 57157433,
  node_id: "MDQ6VXNlcjU3MTU3NDMz",
  avatar_url: "https://avatars2.githubusercontent.com/u/57157433?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ndonyemark",
  html_url: "https://github.com/ndonyemark",
  followers_url: "https://api.github.com/users/ndonyemark/followers",
  following_url: "https://api.github.com/users/ndonyemark/following{/other_user}",
  gists_url: "https://api.github.com/users/ndonyemark/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ndonyemark/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ndonyemark/subscriptions",
  organizations_url: "https://api.github.com/users/ndonyemark/orgs",
  repos_url: "https://api.github.com/users/ndonyemark/repos",
  events_url: "https://api.github.com/users/ndonyemark/events{/privacy}",
  received_events_url: "https://api.github.com/users/ndonyemark/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "Roseoketch",
  id: 33925075,
  node_id: "MDQ6VXNlcjMzOTI1MDc1",
  avatar_url: "https://avatars1.githubusercontent.com/u/33925075?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Roseoketch",
  html_url: "https://github.com/Roseoketch",
  followers_url: "https://api.github.com/users/Roseoketch/followers",
  following_url: "https://api.github.com/users/Roseoketch/following{/other_user}",
  gists_url: "https://api.github.com/users/Roseoketch/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Roseoketch/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Roseoketch/subscriptions",
  organizations_url: "https://api.github.com/users/Roseoketch/orgs",
  repos_url: "https://api.github.com/users/Roseoketch/repos",
  events_url: "https://api.github.com/users/Roseoketch/events{/privacy}",
  received_events_url: "https://api.github.com/users/Roseoketch/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "Eugeneiregi",
  id: 59908155,
  node_id: "MDQ6VXNlcjU5OTA4MTU1",
  avatar_url: "https://avatars1.githubusercontent.com/u/59908155?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Eugeneiregi",
  html_url: "https://github.com/Eugeneiregi",
  followers_url: "https://api.github.com/users/Eugeneiregi/followers",
  following_url: "https://api.github.com/users/Eugeneiregi/following{/other_user}",
  gists_url: "https://api.github.com/users/Eugeneiregi/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Eugeneiregi/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Eugeneiregi/subscriptions",
  organizations_url: "https://api.github.com/users/Eugeneiregi/orgs",
  repos_url: "https://api.github.com/users/Eugeneiregi/repos",
  events_url: "https://api.github.com/users/Eugeneiregi/events{/privacy}",
  received_events_url: "https://api.github.com/users/Eugeneiregi/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "barackmaund1",
  id: 59908804,
  node_id: "MDQ6VXNlcjU5OTA4ODA0",
  avatar_url: "https://avatars1.githubusercontent.com/u/59908804?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/barackmaund1",
  html_url: "https://github.com/barackmaund1",
  followers_url: "https://api.github.com/users/barackmaund1/followers",
  following_url: "https://api.github.com/users/barackmaund1/following{/other_user}",
  gists_url: "https://api.github.com/users/barackmaund1/gists{/gist_id}",
  starred_url: "https://api.github.com/users/barackmaund1/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/barackmaund1/subscriptions",
  organizations_url: "https://api.github.com/users/barackmaund1/orgs",
  repos_url: "https://api.github.com/users/barackmaund1/repos",
  events_url: "https://api.github.com/users/barackmaund1/events{/privacy}",
  received_events_url: "https://api.github.com/users/barackmaund1/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "Alexotieno1717",
  id: 43090738,
  node_id: "MDQ6VXNlcjQzMDkwNzM4",
  avatar_url: "https://avatars0.githubusercontent.com/u/43090738?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Alexotieno1717",
  html_url: "https://github.com/Alexotieno1717",
  followers_url: "https://api.github.com/users/Alexotieno1717/followers",
  following_url: "https://api.github.com/users/Alexotieno1717/following{/other_user}",
  gists_url: "https://api.github.com/users/Alexotieno1717/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Alexotieno1717/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Alexotieno1717/subscriptions",
  organizations_url: "https://api.github.com/users/Alexotieno1717/orgs",
  repos_url: "https://api.github.com/users/Alexotieno1717/repos",
  events_url: "https://api.github.com/users/Alexotieno1717/events{/privacy}",
  received_events_url: "https://api.github.com/users/Alexotieno1717/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "DelivceNdegwa",
  id: 51807298,
  node_id: "MDQ6VXNlcjUxODA3Mjk4",
  avatar_url: "https://avatars1.githubusercontent.com/u/51807298?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/DelivceNdegwa",
  html_url: "https://github.com/DelivceNdegwa",
  followers_url: "https://api.github.com/users/DelivceNdegwa/followers",
  following_url: "https://api.github.com/users/DelivceNdegwa/following{/other_user}",
  gists_url: "https://api.github.com/users/DelivceNdegwa/gists{/gist_id}",
  starred_url: "https://api.github.com/users/DelivceNdegwa/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/DelivceNdegwa/subscriptions",
  organizations_url: "https://api.github.com/users/DelivceNdegwa/orgs",
  repos_url: "https://api.github.com/users/DelivceNdegwa/repos",
  events_url: "https://api.github.com/users/DelivceNdegwa/events{/privacy}",
  received_events_url: "https://api.github.com/users/DelivceNdegwa/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "sumaili-shabani",
  id: 61083807,
  node_id: "MDQ6VXNlcjYxMDgzODA3",
  avatar_url: "https://avatars0.githubusercontent.com/u/61083807?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sumaili-shabani",
  html_url: "https://github.com/sumaili-shabani",
  followers_url: "https://api.github.com/users/sumaili-shabani/followers",
  following_url: "https://api.github.com/users/sumaili-shabani/following{/other_user}",
  gists_url: "https://api.github.com/users/sumaili-shabani/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sumaili-shabani/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sumaili-shabani/subscriptions",
  organizations_url: "https://api.github.com/users/sumaili-shabani/orgs",
  repos_url: "https://api.github.com/users/sumaili-shabani/repos",
  events_url: "https://api.github.com/users/sumaili-shabani/events{/privacy}",
  received_events_url: "https://api.github.com/users/sumaili-shabani/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "David5627",
  id: 70572648,
  node_id: "MDQ6VXNlcjcwNTcyNjQ4",
  avatar_url: "https://avatars2.githubusercontent.com/u/70572648?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/David5627",
  html_url: "https://github.com/David5627",
  followers_url: "https://api.github.com/users/David5627/followers",
  following_url: "https://api.github.com/users/David5627/following{/other_user}",
  gists_url: "https://api.github.com/users/David5627/gists{/gist_id}",
  starred_url: "https://api.github.com/users/David5627/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/David5627/subscriptions",
  organizations_url: "https://api.github.com/users/David5627/orgs",
  repos_url: "https://api.github.com/users/David5627/repos",
  events_url: "https://api.github.com/users/David5627/events{/privacy}",
  received_events_url: "https://api.github.com/users/David5627/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "andyjohn23",
  id: 69298387,
  node_id: "MDQ6VXNlcjY5Mjk4Mzg3",
  avatar_url: "https://avatars2.githubusercontent.com/u/69298387?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/andyjohn23",
  html_url: "https://github.com/andyjohn23",
  followers_url: "https://api.github.com/users/andyjohn23/followers",
  following_url: "https://api.github.com/users/andyjohn23/following{/other_user}",
  gists_url: "https://api.github.com/users/andyjohn23/gists{/gist_id}",
  starred_url: "https://api.github.com/users/andyjohn23/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/andyjohn23/subscriptions",
  organizations_url: "https://api.github.com/users/andyjohn23/orgs",
  repos_url: "https://api.github.com/users/andyjohn23/repos",
  events_url: "https://api.github.com/users/andyjohn23/events{/privacy}",
  received_events_url: "https://api.github.com/users/andyjohn23/received_events",
  type: "User",
  site_admin: false
  }
  ];